### PR TITLE
Prometheus/Grafana setup

### PR DESCRIPTION
**Pull request by Nutomic**
## Summary of changes
- Setup Prometheus and Grafana in docker-compose with `http://localhost:9955/api/v1/metrics` as scraping target
- Readme with instructions to get started
- Very basic Grafana dashboard with a single metric to show that it works

### Reference issue to close (if applicable)
- References #388 

-----
### Code Checklist 

- [x] Tested
- [x] Documented

### CODE REVIEW

**Comment by drewstone** [comment]
What's the status of this?

**Comment by Nutomic** [comment]
Im currently working on the substrate fees, will get back to this afterwards. Right now its not working due to the invalid token error I posted above.

**Comment by Nutomic** [comment]
Just got back to this. The metrics API endpoint was wrong, it shouldnt wrap the data in json but serve it directly as plain string. This means the basic setup is finished and you can view stats, but I havent started building a proper dashboard yet.

I think the best way to continue with this is to merge and deploy it (specifically the change to metrics endpoint). Then I can connect to a live relayer for testing and building a dashboard. That should be more effective than relying on local test data.

**Review by salman01zp — APPROVED** [review]
LGTM..! Great work @Nutomic

**Review by shekohex — APPROVED** [review]

**Pull request merged**
