### PR TITLE
Changes to CI conditions, push new commits on develop to `edge` tag

### PR DESCRIPTION
**Pull request by Nutomic**
## Summary of changes
- Disable lints, integration tests etc on main and develop branches. These are unnecessary because code can only be added through pull request and not pushed directly to those branches.
- `edge` image is currently only built on main branch. Im changing it to develop.

### Reference issue to close (if applicable)
- Ref https://github.com/webb-tools/relayer/issues/449

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

### CODE REVIEW

**Review by shekohex — APPROVED** [review]
LGTM!

**Comment by shekohex** [comment]
Should be merged after #458

**Comment by Nutomic** [comment]
I added a cronjob on relayers server which pulls and deploys new docker images every hour (can be changed with `crontab -e`). After this PR is merged and edge image is built, we just need to change `$DEV_RELAYER_VERSION` from release to edge.

**Comment by shekohex** [comment]
> I added a cronjob on relayers server which pulls and deploys new docker images every hour (can be changed with `crontab -e`). After this PR is merged and edge image is built, we just need to change `$DEV_RELAYER_VERSION` from release to edge.

I'm working on fixing this flaky tests and maybe it is actually a bug in our leaf caching.

**Pull request merged**
