### PR TITLE
Switch web framework to axum

### LINKED ISSUE #333: [TASK] Migrate from warp to axum web-framework
### Overview

After doing a simple research on the current Rust web framewroks, turns out that [axum](https://github.com/tokio-rs/axum) looks a good fit for us.

### Task Checklist

Migrate all these endpoints:

- [ ] `/api/v1/info`
- [ ] `api/v1/ip`
- [ ] `api/v1/leaves/evm`
- [ ] `api/v1/leaves/substrate`
- [ ] `api/v1/encrypted_outputs/evm`
- [ ] `api/v1/encrypted_outputs/substrate`
- [ ] `api/v1/metrics`
- [ ] `api/v1/metrics/evm`
- [ ] `api/v1/metrics/substrate`
- [ ] `api/v1/ws` (Websocket)

### PR DESCRIPTION
**Pull request by Nutomic**
## Summary of changes
- Moved `SledStore` into `RelayerContext` because axum can only have a single `State`
- Migrate endpoints
  - [x] `/api/v1/info`
  - [x] `api/v1/ip`
  - [x] `api/v1/leaves/evm`
  - [x] `api/v1/leaves/substrate`
  - [x] `api/v1/encrypted_outputs/evm`
  - [x] `api/v1/encrypted_outputs/substrate`
  - [x] `api/v1/metrics`
  - [x] `api/v1/metrics/evm`
  - [x] `api/v1/metrics/substrate`
  - [x] `ws` (Websocket)

### Reference issue to close (if applicable)
- Closes #333

-----
### Code Checklist 

- [x] Tested
- [x] Documented

### CODE REVIEW

**Comment by shekohex** [comment]
@Nutomic You should rebase your branch, you are building on top of the fee estimate branch, you better create these changes off main branch.

**Comment by Nutomic** [comment]
I rebased the fee estimate branch and rebased this one on fee estimate so its okay. But really I should have merged main into fee estimate, would have been much easier.

**Comment by Nutomic** [comment]
This is ready to merge, use [this link](https://github.com/webb-tools/relayer/pull/336/files/1bdb9892351ca066697c64ce2d764928e4c1aaf5..00107897630b21f045fc653aff5fd8f9ff38bdf6) to view only changes from this commit excluding #330 (btw let me know if theres anything missing to get that one merged).

The conversion was surprisingly easy, only websocket caused some problems (which are fixed).

**Review by shekohex — APPROVED** [review]

**Comment by shekohex** [comment]
@Nutomic We did merge the Fees PR, but this now got Conflicting files, lets resolve those and do another review.

**Comment by Nutomic** [comment]
I fixed the conflicts.

**Review by shekohex — APPROVED** [review]

**Pull request merged**
