### PR TITLE
Substrate code cleanup

### PR DESCRIPTION
**Pull request by salman01zp**
## Summary of changes
- [x] Remove substrate event watchers for Vanchor and  Signature bridge
- [x] Remove Private tx relaying for substrate
- [x] Remove substrate API services
- [x] Remove substrate config for Vanchor and Signature bridge pallets
- [x] Remove bridge watcher trait

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

### CODE REVIEW

**Comment by shekohex** [comment]
@salman01zp is this now ready to review? is there any other cleanup things we should consider?

**Comment by salman01zp** [comment]
I have removed almost everything related to the substrate(vanchor/signature bridge around). 
Looking into why most of the tests are not passing, but else is good to review

**Comment by shekohex** [comment]
> I have removed almost everything related to the substrate(vanchor/signature bridge around). 

Good
> Looking into why the tests are not passing, but else is good to review

Is it passing locally? Which one is failing?

**Comment by shekohex** [comment]
In [`640bd15` (#554)](https://github.com/webb-tools/relayer/pull/554/commits/640bd155bd125408c6286bb49547301ef362c42f) you removed substrate tx queue! we still need that for DKG Transactions. so @salman01zp could you please bring this back.

**Comment by shekohex** [comment]
Fixed the substrate tx queue errors and improved the tx dry-run failure detection. this should be ready very soon.

**Review by shekohex — APPROVED** [review]

**Pull request merged**
